#version: '3.7'
#
#services:
#
#  consul-server1:
#    image: consul:1.9.3
#    container_name: consul-server1
#    restart: always
#    volumes:
#     - ./server1.json:/consul/config/server1.json:ro
#     - ./certs/:/consul/config/certs/:ro
#    networks:
#      - consul
#    ports:
#      - "8500:8500"
#      - "8600:8600/tcp"
#      - "8600:8600/udp"
#    command: "agent -bootstrap-expect=3"
#
#  consul-server2:
#    image: consul:1.9.3
#    container_name: consul-server2
#    restart: always
#    volumes:
#     - ./server2.json:/consul/config/server2.json:ro
#     - ./certs/:/consul/config/certs/:ro
#    networks:
#      - consul
#    command: "agent -bootstrap-expect=3"
#
#  consul-server3:
#    image: consul:1.9.3
#    container_name: consul-server3
#    restart: always
#    volumes:
#     - ./server3.json:/consul/config/server3.json:ro
#     - ./certs/:/consul/config/certs/:ro
#    networks:
#      - consul
#    command: "agent -bootstrap-expect=3"
#
#  consul-client:
#    image: consul:1.9.3
#    container_name: consul-client
#    restart: always
#    volumes:
#     - ./client.json:/consul/config/client.json:ro
#     - ./certs/consul-agent-ca.pem:/consul/config/certs/consul-agent-ca.pem:ro
#    networks:
#      - consul
#    command: "agent"
#
#networks:
#  consul:
#    driver: bridge


version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  consul-demo: